# Generated by Django 5.0.4 on 2024-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_car',
            name='car_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
