# Generated by Django 5.0.4 on 2024-05-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_slug'),
        ('car', '0005_alter_add_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_car',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='brand.brand'),
        ),
    ]
